update algo MNx and test
IGNF/pdal-ign-plugin pull request #24
Opened 2024-09-17 09:04 UTC by alavenant

2024-09-30 12:34 UTC, leavauchier requested changes

2024-09-30 12:34 UTC, leavauchier commented on test/pdal_ign_macro/test_mark_points_to_use_for_digital_models_with_new_dimension.py
> +from pdaltools.las_remove_dimensions import remove_dimensions_from_las
la fonction n'a pas l'air d'être utilisée => import à enlever

2024-09-30 12:34 UTC, leavauchier commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        + macro.build_condition("Classification", [2, 3, 4, 5, 6, 9, 67])
l'ajout des parenthèse a l'air d'être un reste de l'ancien code qui ne marchait pas sans. Je pense qu'il faut garder ces lignes commes elles étaient avant la MR

2024-09-30 12:34 UTC, leavauchier commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,  # prendre tous les points qui sont en dessous des points pont (condition_ref)
Normalement, "-1" fonctionne (900 avait été mis à la place à cause d'une incompréhension au début du dev, je pense qu'on peut laisser -1)

2024-09-30 12:34 UTC, leavauchier commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        condition_ref=f"Classification==2 && PT_ON_BUILDING==0 && PT_VEG_DSM==0",
modif à ne pas garder (`f` inutile vu qu'on n'a pas de variable dans la chaîne de caractère), jd'ailleurs normalement black râle normalement si on laisse le `f`/
Tu pourras repasser les pre-commits hooks sur ce commit pour vérifier qu'il n'y a pas de problèmes de syntaxe stp ?

2024-09-30 12:34 UTC, leavauchier commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,
Normalement, "-1" fonctionne (900 avait été mis à la place à cause d'une incompréhension au début du dev, je pense qu'on peut laisser -1)

2024-09-30 12:34 UTC, leavauchier commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,  # prendre tous les points qui sont en dessous des points pont (condition_ref)
Normalement, "-1" fonctionne (900 avait été mis à la place à cause d'une incompréhension au début du dev, je pense qu'on peut laisser -1)

2024-09-30 12:34 UTC, leavauchier commented on RELEASE_NOTES.md
> +Update algorithm of [mark_points_to_use_for_digital_models_with_new_dimension](pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py),
Si jamais tu as un résumé de ce qui a changé dans l'algo, ça peut être utile poru la suite.
Si j'ai bien compris c'est surtout les points virtuels qui ont des changements

2024-09-30 12:54 UTC, alavenant commented on test/pdal_ign_macro/test_mark_points_to_use_for_digital_models_with_new_dimension.py
> +from pdaltools.las_remove_dimensions import remove_dimensions_from_las
fix

2024-09-30 12:58 UTC, alavenant commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,
ok

2024-09-30 12:58 UTC, alavenant commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,  # prendre tous les points qui sont en dessous des points pont (condition_ref)
ok

2024-09-30 13:33 UTC, alavenant commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,  # prendre tous les points qui sont en dessous des points pont (condition_ref)
Les tests ne fonctionnent plus en modifiant 900 à -1. J'essaye de comprendre pourquoi.

2024-09-30 13:33 UTC, alavenant commented on RELEASE_NOTES.md
> +Update algorithm of [mark_points_to_use_for_digital_models_with_new_dimension](pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py),
2/3 ajouts

2024-09-30 15:18 UTC, leavauchier commented on pdal_ign_macro/mark_points_to_use_for_digital_models_with_new_dimension.py
> +        max2d_below=900,  # prendre tous les points qui sont en dessous des points pont (condition_ref)
> Les tests ne fonctionnent plus en modifiant 900 à -1. J'essaye de comprendre pourquoi.

Dans ce cas c'est peut-être dans la fonction que ça foire (ou les points virtuels)

2024-10-03 10:56 UTC, leavauchier requested changes

2024-10-03 10:56 UTC, leavauchier commented on test/test_radius_assign.py
>      def func_test(pt):
ça m'embête de tester cette fonction en utilisant la même logique que celle qui est dans l'algo, surtout maintenant qu'on s'est retourné le cerveau sur cette logique. Est-ce qu'il n'y aurait pas un moyen de vérifier le résultat d'une autre façon ? Dans le cas contraire, est-ce que tu as pu regarder les nuages de points créés et voir que c'était cohérent par exemple ?

2024-10-03 13:18 UTC, alavenant commented on test/test_radius_assign.py
>      def func_test(pt):
En phase avec toi. J'ai ajouté des tests spécifiques avec des conditions faciles à tester.

2024-10-03 15:40 UTC, leavauchier approved these changes
C'est bon pour moi, j'ai juste un poil pinaillé

2024-10-03 15:40 UTC, leavauchier commented on test/test_radius_assign.py
> +def test_radius_assign_2d_cylinder_above_bellow_null():
typo 
```suggestion
def test_radius_assign_2d_cylinder_above_below_null():
```

2024-10-03 15:40 UTC, leavauchier commented on test/test_radius_assign.py
> +        if distance_i < distance_radius and distance_z == 0:
avec des points aléatoires, t'as quasi aucune chance d'avoir `distance_z = 0`, donc ton test vérifie surtout que tu ne gardes aucun point

2024-10-03 16:24 UTC, alavenant commented on test/test_radius_assign.py
> +        if distance_i < distance_radius and distance_z == 0:
si parce qu'il y a deux points non aléatoire au début, dont un à distance_z = 0

2024-10-04 07:05 UTC, alavenant commented on test/test_radius_assign.py
> +        if distance_i < distance_radius and distance_z == 0:
J'ai complété avec quelques tests

2024-10-10 07:58 UTC, leavauchier approved these changes

2024-10-10 07:58 UTC, merged